% BUILDDRISHTIMITRAAPP App Designer creation handoff.
% An .mlapp is a MATLAB-owned binary artifact and must be authored/validated in
% App Designer. This script intentionally creates no fake .mlapp file.
assert(exist('appdesigner','file')==4 || exist('uifigure','file')==2, ...
 'DrishtiMitra:AppDesignerMissing','Open this project in MATLAB with App Designer installed.');
error('DrishtiMitra:ManualAppDesignerStep', ...
 ['Create DrishtiMitraApp.mlapp in App Designer with callbacks: Load Image -> assessQuality -> ', ...
  'gradeImage/overlay display -> gradCAM -> generateClinicalReport -> sim(ScreeningWorkflow). ', ...
  'A MATLAB runtime is required; no plain .m UI is substituted.']);
